POST https://loop-backend-render.onrender.com/api/User/firebase-auth
Content-Type: application/json

{
    "IdToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ1YTZjMGMyYjgwMDcxN2EzNGQ1Y2JiYmYzOWI4NGI2NzYxMjgyNjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbG9vcC1kODI5MSIsImF1ZCI6Imxvb3AtZDgyOTEiLCJhdXRoX3RpbWUiOjE3NjQwOTIyMzYsInVzZXJfaWQiOiI4a3FWTmZFNHBwUTdieDNBYjh5ZUhyb216cFgyIiwic3ViIjoiOGtxVk5mRTRwcFE3YngzQWI4eWVIcm9tenBYMiIsImlhdCI6MTc2NDA5MjIzNiwiZXhwIjoxNzY0MDk1ODM2LCJlbWFpbCI6InRlc3QxMjNAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QxMjNAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.MSJ4FMeSXRuSyMf_lnbhQh-aBKXt8faAkNzcEfFv0Zdsw1wXePQ712WIPsSG3mAuqrjzEyMrjUhT4X4z61ZXnlofuG80854MGiOKskEj74lz5Lzg0VvJ_rLCodI_k9leX2XYJHuxyfquOWOttZIPIAU8d02027oV4oH_aXe3313ZBYOrhlH57KnIDgh8lL7tRZ3E1v-791FjmiNP7PGpp3gulX-Jw2RSbNjf1CALBLORtsd4EuHFQAWRYIUV2m0SmQmOjCu8gHDYI8LgZVxag_bxLJ_3bS5yPvVy-o6vAC--32nR0yy9IIPoP1y5_W0If9Wb9wBdHuz7BnSNCxzR_g" 
}