POST https://loop-backend-render.onrender.com/api/User/firebase-auth
Content-Type: application/json

{
    "IdToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ1YTZjMGMyYjgwMDcxN2EzNGQ1Y2JiYmYzOWI4NGI2NzYxMjgyNjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbG9vcC1kODI5MSIsImF1ZCI6Imxvb3AtZDgyOTEiLCJhdXRoX3RpbWUiOjE3NjQwODkwNDAsInVzZXJfaWQiOiI4a3FWTmZFNHBwUTdieDNBYjh5ZUhyb216cFgyIiwic3ViIjoiOGtxVk5mRTRwcFE3YngzQWI4eWVIcm9tenBYMiIsImlhdCI6MTc2NDA4OTA0MCwiZXhwIjoxNzY0MDkyNjQwLCJlbWFpbCI6InRlc3QxMjNAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QxMjNAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.d4VyNck6cRKXqbk42-AZHXg-o_82u2oYZW-DMrmr9ExyjJTCV9_atxlf_dZOmsSfSpFVk4UNk1ZrjyWt5LGh9AGSEZybAKNKVtY0JtXcN_A2_klX9ql6oTR87G52u6xL7RZTlt4Z_g5MLZn2H7hSTOsLEewuBY4vBUSCjwIxKiYTjSM1lEjhDMF0S2lEA7wEwW5v6GLZnXlH_viwRHe_bfzNZBVS_kRCv20l_XLgOPSCruhW7uZiEzOEsFOIXTRDcd23hXhkhy7nLwxESmYgimJyvtwScgQssSDhR4n7zIqHJspubBYLlTm5ujMEv3Pm_19aKHiMQEbgpDZjtzD7Tg" 
}