POST https://loop-backend-render.onrender.com/api/User/firebase-auth
Content-Type: application/json

{
    "IdToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ1YTZjMGMyYjgwMDcxN2EzNGQ1Y2JiYmYzOWI4NGI2NzYxMjgyNjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbG9vcC1kODI5MSIsImF1ZCI6Imxvb3AtZDgyOTEiLCJhdXRoX3RpbWUiOjE3NjQwOTM5MTksInVzZXJfaWQiOiI4a3FWTmZFNHBwUTdieDNBYjh5ZUhyb216cFgyIiwic3ViIjoiOGtxVk5mRTRwcFE3YngzQWI4eWVIcm9tenBYMiIsImlhdCI6MTc2NDA5MzkxOSwiZXhwIjoxNzY0MDk3NTE5LCJlbWFpbCI6InRlc3QxMjNAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QxMjNAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.O8KEj0Qo7yoXfCvIy6BtML99GZ0Qwe2CIhaRh0bmT17_UpijksASYmYvaY4dnpSEBDwQhbebd_uzzGIB6xmUqo3N50wSKnyUFuWim3lK5XeH9qzlVP2w-NoIhwTO8CQZ7q_1uLYA7n7F0As5JPl3bd67zZvVykH8U1eYAFPd_YAYRkRhpAx2LzXNZlGOh1SNLRXRfxh8hhsKt8OA4YWT2k4HLYG_ilF6Fsa_B23ec04J-fhc7DHeC_c7ViThKRItzEdo7US_XO4rQLKSiVXXhq0YD218OwPoT16EYYSS2813WXgyDFHwgzFeEMCckgv4GA5DKpH-nG7eikLZQXsCiA" 
}