GET https://loop-backend-render.onrender.com/api/Product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI3NjA3NDhhYi0zYmY5LTQxNGItYjI1YS05Yzk3NjY3NDlhODgiLCJ1bmlxdWVfbmFtZSI6IlVzdWFyaW8gRmlyZWJhc2UiLCJlbWFpbCI6InRlc3QxMjNAZW1haWwuY29tIiwibmJmIjoxNzY0MDk3MzU5LCJleHAiOjE3NjQxMTUzNTksImlhdCI6MTc2NDA5NzM1OX0.rHT3suuTRuDKj02KhTCMfNmyBhohtYVpPblRRX9AZuQ}
